
[origins]

	[origins."origins-classes:nitwit"]
		enabled = true

	[origins."origins:enderian"]
		enabled = true

	[origins."origins:feline"]
		enabled = true

	[origins."origins-classes:warrior"]
		enabled = true
		"origins-classes:more_attack_damage" = true
		"origins-classes:less_shield_slowdown" = true

	[origins."origins:elytrian"]
		enabled = true

	[origins."toomanyorigins:hare"]
		enabled = true
		"toomanyorigins:hot_hops" = true
		"toomanyorigins:waterskipper" = true
		"toomanyorigins:extra_step_height" = true
		"toomanyorigins:prevent_movement_checks" = true
		"toomanyorigins:cancel_out_sprint_disable_on_hit" = true

	[origins."origins-classes:explorer"]
		enabled = true
		"origins-classes:explorer_kit" = true
		"origins-classes:no_sprint_exhaustion" = true

	[origins."origins_minus:voidthing"]
		enabled = true
		"origins_minus:blink" = true
		"origins_minus:reach" = true
		"origins_minus:wraparound" = true
		"origins:ender_particles" = true
		"origins_minus:voidthing_particles" = true

	[origins."origins_minus:avian"]
		enabled = true
		"origins_minus:flap" = true
		"origins_minus:glide" = true
		"origins_minus:like_air" = true
		"origins_minus:wingspan" = true
		"origins_minus:aerodynamic" = true

	[origins."origins:phantom"]
		enabled = true

	[origins."origins-classes:beastmaster"]
		enabled = true
		"origins-classes:tamed_animal_boost" = true
		"origins-classes:tamed_potion_diffusal" = true

	[origins."origins-classes:merchant"]
		enabled = true
		"origins-classes:trade_availability" = true
		"origins-classes:rare_wandering_loot" = true

	[origins."origins-classes:rancher"]
		enabled = true
		"origins-classes:twin_breeding" = true
		"origins-classes:more_animal_loot" = true

	[origins."origins:blazeborn"]
		enabled = true

	[origins."origins:avian"]
		enabled = true

	[origins."origins_minus:wildling"]
		enabled = true
		"origins_minus:energetic" = true
		"origins_minus:bound" = true
		"origins_minus:carefree" = true

	[origins."origins-classes:archer"]
		enabled = true
		"origins-classes:no_projectile_divergence" = true
		"origins-classes:less_bow_slowdown" = true

	[origins."origins-classes:farmer"]
		enabled = true
		"origins-classes:more_crop_drops" = true
		"origins-classes:better_bone_meal" = true

	[origins."origins-classes:miner"]
		enabled = true
		"origins-classes:more_stone_break_speed" = true
		"origins-classes:no_mining_exhaustion" = true

	[origins."toomanyorigins:withered"]
		enabled = true
		"toomanyorigins:affliction" = true
		"toomanyorigins:soul_siphon" = true
		"origins:nether_spawn" = true
		"toomanyorigins:hell_raised" = true
		"toomanyorigins:spirit_strider" = true
		"toomanyorigins:deathly_digestion" = true
		"toomanyorigins:unholy" = true

	[origins."origins-classes:cook"]
		enabled = true
		"origins-classes:better_crafted_food" = true
		"origins-classes:more_smoker_xp" = true

	[origins."toomanyorigins:hisskin"]
		enabled = true
		"toomanyoriginsminus:buildup" = true
		"toomanyorigins:aerial_stability" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins-classes:lumberjack"]
		enabled = true
		"origins-classes:tree_felling" = true
		"origins-classes:more_planks_from_logs" = true

	[origins."origins_minus:mer"]
		enabled = true
		"origins_minus:water_breathing" = true
		"origins_minus:swim_speed" = true
		"origins_minus:water_vision" = true
		"origins_minus:aqua_affinity" = true
		"origins_minus:harvest_seagrass" = true
		"origins_minus:edible_seagrass" = true
		"origins:like_water" = true
		"origins_minus:countercurrent" = true
		"origins_minus:ocean_free" = true
		"origins_minus:osmoregulation" = true
		"origins_minus:mer_particles" = true

	[origins."origins_minus:dryad"]
		enabled = true
		"origins_minus:sunlight" = true
		"origins_minus:no_hunger" = true
		"origins_minus:vine_whip" = true
		"origins_minus:bioluminescence" = true
		"origins_minus:leaf_phasing" = true
		"origins_minus:leaves_fall_immunity" = true
		"origins_minus:plant_fall_resistance" = true
		"origins_minus:old_friends" = true
		"origins_minus:dryad_particles" = true

	[origins."toomanyorigins:swarm"]
		enabled = true
		"toomanyoriginsminus:hover" = true
		"toomanyorigins:beekeeper" = true

	[origins."origins:shulk"]
		enabled = true

	[origins."origins-classes:cleric"]
		enabled = true
		"origins-classes:potion_bonus" = true
		"origins-classes:better_enchanting" = true

	[origins."toomanyorigins:dragonborn"]
		enabled = true
		"toomanyorigins:draconic_breath" = true
		"toomanyorigins:block_synergistics" = true
		"toomanyorigins:weaponry_pride" = true
		"toomanyorigins:zenith_scales" = true
		"toomanyorigins:rough_claws" = true

	[origins."origins_minus:sanguine"]
		enabled = true
		"origins_minus:blood" = true
		"origins_minus:no_hunger" = true
		"origins_minus:frenzy" = true
		"origins_minus:nightstalker" = true
		"origins_minus:spill" = true

	[origins."origins_minus:starved"]
		enabled = true
		"origins_minus:hunger_prevent_death" = true
		"origins_minus:fast_eating" = true
		"origins_minus:fast_eating_tooltips" = true
		"origins_minus:snacking_saturation" = true
		"origins_minus:satiation" = true
		"origins_minus:ravenous" = true
		"origins_minus:buffet_strategy" = true

	[origins."origins:merling"]
		enabled = true

	[origins."origins:arachnid"]
		enabled = true

	[origins."origins_minus:steadfast"]
		enabled = true
		"origins_minus:brace" = true
		"origins_minus:rescue" = true

	[origins."origins_minus:hellspawn"]
		enabled = true
		"origins_minus:fire_immunity" = true
		"origins_minus:lava_vision" = true
		"origins_minus:lava_swimming" = true
		"origins_minus:fire_punch" = true
		"origins_minus:lava_fall_immunity" = true
		"origins:flame_particles" = true
		"origins_minus:flamehardy" = true
		"origins_minus:molten_cruise" = true
		"origins_minus:temper_temper" = true
		"origins_minus:hellspawn_particles" = true

	[origins."origins_minus:weaver"]
		enabled = true
		"origins_minus:echolocation" = true
		"origins_minus:rappel" = true
		"origins_minus:suffocation_immunity" = true
		"origins_minus:web_affinity" = true
		"origins:master_of_webs_no_slowdown" = true
		"origins_minus:sticky_situations" = true
		"origins:no_cobweb_slowdown" = true

	[origins."origins-classes:blacksmith"]
		enabled = true
		"origins-classes:quality_equipment" = true
		"origins-classes:efficient_repairs" = true

	[origins."origins-classes:rogue"]
		enabled = true
		"origins-classes:sneaky" = true
		"origins-classes:stealth" = true
		"origins-classes:stealth_core" = true

